# ------------------------------------------------------- #
#             config file for name of system
# ------------------------------------------------------- #
general:
  debug_level: info
  version: v99-99-99

# ------------------------------------------------------- #
#                      Config header 2
# ------------------------------------------------------- #
